language: python

matrix:
  allow_failures:
  - dist: bionic
  include:
  - name: "Python 2.7 on Trusty 14.04 LTS"
    python: "2.7"
    dist: trusty
  - name: "Python 2.7 on Xenial 16.04 LTS"
    python: "2.7"
    dist: xenial
  - name: "Python 2.7 on Bionic 18.04 LTS"
    python: "2.7"
    dist: bionic

  - name: "Python 3.5 on Trusty 14.04 LTS"
    python: "3.5"
    dist: trusty
  - name: "Python 3.5 on Xenial 16.04 LTS"
    python: "3.5"
    dist: xenial
  # Travis CI does not support Python 3.5 on Bionic

  - name: "Python 3.6 on Trusty 14.04 LTS"
    python: "3.6"
    dist: trusty
  - name: "Python 3.6 on Xenial 16.04 LTS"
    python: "3.6"
    dist: xenial
  - name: "Python 3.6 on Bionic 18.04 LTS"
    python: "3.6"
    dist: bionic

  # Travis CI does not support Python 3.7 on Trusty
  - name: "Python 3.7 on Xenial 16.04 LTS"
    python: "3.7"
    dist: xenial
  - name: "Python 3.7 on Bionic 18.04 LTS"
    python: "3.7"
    dist: bionic

env:
  global:
    - BLUEZ_SRC_DIR="./contrib/bluez"
    - LOCAL_INCLUDE_DIR="./include"

os:
  - linux

before_install:

  - git clone https://git.kernel.org/pub/scm/bluetooth/bluez.git -n $BLUEZ_SRC_DIR && cd $BLUEZ_SRC_DIR && git checkout $(git describe --tags $(git rev-list --tags='[0-9]*.[0-9]*' -n 1)) && cd -
  - mkdir -p $LOCAL_INCLUDE_DIR/bluetooth && cp $BLUEZ_SRC_DIR/lib/*.h $LOCAL_INCLUDE_DIR/bluetooth
  - pip install flake8 -r requirements.txt

install:
  - CFLAGS="-I$LOCAL_INCLUDE_DIR" python setup.py build
  - python setup.py install

script:
  - flake8 . --count --exclude=./.*,./contrib/bluez/test/sap_client.py --select=E9,F63,F7,F82 --show-source --statistics
  - python examples/simple/inquiry.py || true

# Use VMs instead of Docker; bluez is not on the approved package whitelist
# https://github.com/travis-ci/apt-package-whitelist/issues/2463
sudo: true

addons:
  apt:
    packages:
      - bluez
      - libbluetooth-dev
